trainingInput:
  scaleTier: CUSTOM
  # Configure a master worker with 4 K80 GPUs
  masterType: standard_gpu
  # Configure 9 workers, each with 4 K80 GPUs
  workerCount: 2
  workerType: standard_gpu
  # Configure 3 parameter servers with no GPUs
  parameterServerCount: 1
  parameterServerType: standard